### ISSUE TITLE
Export to variable options

### ISSUE THREAD

**Issue by sushiinudesu** [cwtools/cwtools-eu4-config#329]
1. Inside of scripted effect with params u can export these params to variables:
```
export_to_variable = { 
                 which = hex_num_of_quest_provinces 
                 value = $amount$ 
 }
```

2. On province scope u can export `culture` to variables.

Probably some other things too, but these are the ones I found.

**Comment by sushiinudesu** [comment]
Looking at other issues I now realize  [this](https://github.com/cwtools/cwtools-eu4-config/issues/112) might be related

**Comment by 17blue17** [comment]
As mentioned in the known issues on the Paradox mod forum cwtools thread Scripted triggers and effects cause CWTools lots of problems.  Things like $ $  and  [[ ] and using " " instead of { } all cause CWTools problems which the author says can not be fixed.  For some of the [[ ] stuff I was able to hard code answers but it was a real pain and then someone complained I was hard coding stuff.   No way to win.   I have begged Paradox to reconsider using "  " instead of { } as it is the absolute worst for me  to try to deal with.  They are thinking about it but I don't have much hope.     

As far as export_to_variable I have been able to hard code a long list of valid items from the main game excluding $  $ stuff.  Culture is not on that list as I did not see it used in game but if you are sure culture works then I will add it in a few minutes.

**Comment by sushiinudesu** [comment]
Is there absolutely no way? I've added `value = enum[scripted_effect_params_dollar]` rule to the validation and as u can see it says that it can also expect a "Scripted effect parameter", but still is not validating it.

![Screenshot (36)](https://github.com/cwtools/cwtools-eu4-config/assets/40493835/132ab1a3-9cd5-4fbb-a968-b2815b3f113e)

**Comment by 17blue17** [comment]
Neither I nor Maxice8 understand how cwtools works with scripted effects or triggers in the  F (sp?) source code.  When I ask Caligula who used to be on the Eu4 Paradox team and now is on the Stellaris Paradox team he says there is nothing I can do with the $ $ stuff.   Even if you get something working for you how does that help all the regular users that have standard code?   Sorry I like to have as few errors as possible and I am proud that outside the common scripted triggers and effects that I have gotten rid of almost all of them.  I even hard coded a bunch of stuff for the " " code but it got to be too much and some remains.    Dayshine is the author and he says the #F code is a pain and will not do what he wants.

**Comment by sushiinudesu** [comment]
OK. Thanks for your hard work)
